#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   RSI-MA Performance Analytics Dashboard - Quick Start        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ All files are ready!"
echo "✅ Dependencies installed!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 TO VIEW THE DASHBOARD:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Start Backend (Terminal 1):"
echo "    cd /workspace/backend"
echo "    python3 api.py"
echo ""
echo "2️⃣  Start Frontend (Terminal 2):"
echo "    cd /workspace/frontend"
echo "    npm run dev"
echo ""
echo "3️⃣  Open Browser:"
echo "    http://localhost:3000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 OPTIONAL: Run Backtest First (recommended for faster loading)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "    cd /workspace/backend"
echo "    python3 enhanced_backtester.py"
echo ""
echo "    This pre-loads data for all 8 tickers (takes 2-5 minutes)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Documentation:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "    VIEW_DASHBOARD.md   - Step-by-step viewing guide"
echo "    QUICKSTART.md       - 5-minute quick start"
echo "    README.md           - Complete documentation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
